spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:newsfeed}
    username: ${USER_NAME:root}
    password: ${PASSWORD:wlsl1234!!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true